### ISSUE TITLE
Add check for sane database format

### ISSUE THREAD

**Issue by byt3bl33d3r** [Porchetta-Industries/CrackMapExec#148]
The database schema is a work in progress and changes rapidly as new features get implemented or removed. Should add a check to make sure the current db file has the right schema to avoid issues like #146 .

**Comment by mpgn** [comment]
Hello,

Thanks for the issue, it is now fixed on the last public release of CrackMapExec https://github.com/mpgn/CrackMapExec v6.0.0

Regards,

mpgn
