### ISSUE TITLE
Ability to clear the database (without just blowing away the ~/.cme directory)

### ISSUE THREAD

**Issue by bucky67gto** [Porchetta-Industries/CrackMapExec#189]
Any idea how to clear the database for a new engagement?

**Comment by decidedlygray** [comment]
Is there any reason not to just revert to checked out HEAD commit? It would wipe out any local changes:

```got reset --hard HEAD```

If you made any local changes you would lose them, but if you haven't it should also now be easy fetch new changes. Tthis repo is actively maintained and new stuff is added and fixed all the time.

**Comment by byt3bl33d3r** [comment]
@bucky67gto you can just delete the ~/.cme directory, it will be re-created on runtime. I definitely agree there should be a better way of doing this though.

**Comment by byt3bl33d3r** [comment]
Or alternatively just delete the smb.db file in the ~/.cme directory ;)

**Comment by mpgn** [comment]
Hello,

Thanks for the issue, it is now fixed on the last public release of CrackMapExec https://github.com/mpgn/CrackMapExec v6.0.0

Regards,

mpgn
