### ISSUE TITLE
SMBv2 support

### ISSUE THREAD

**Issue by ztencmcp** [Porchetta-Industries/CrackMapExec#198]
I found that CME only works with SMBv1 enabled domain PCs and if PCs with SMBv2 enabled couldn't be pwned. Is that ture?

**Comment by byt3bl33d3r** [comment]
v4 supports SMBv1 and SMBv3, mostly because I have yet to run into any client environment with only SMBv2. Will add support for this soon

**Comment by ztencmcp** [comment]
@byt3bl33d3r Thanks for your answer. And i have another question,that is when i use CME to connect some PCs in domain envirement there is nothing displayed(error or hint). What's this question? Thank you!

**Comment by Marshall-Hallenbeck** [comment]
CME has supported v3 for a while now. @mpgn I believe this can be closed.
