### ISSUE TITLE
Improvement: opsec auto-accept flag

### ISSUE THREAD

**Issue by ebrinkster** [Porchetta-Industries/CrackMapExec#213]
## Steps to reproduce

1. Install CME v4.0.0.dev 'Sercurty'
2. Run CME v4.0.0.dev 'Sercurty' against multiple workstations using the module enum_chrome within a bash script.

## Command string used
`cme smb /path/to/ips.txt -M enum_chrome -d domain -u username -p password`

## CME verbose output (using the --verbose flag)
`[!] Module is not opsec safe, are you sure you want to run this? [Y/n]`

## OS
Kali Linux (latest as of post date)

## Target OS
Kali Linux (latest as of post date)

## Detailed issue explanation
I run CME in scripts that auto fill ips.txt, username, domain and password.  The enum_chrome module (among others) requires user input (Y or n) because it is not opsec safe.  Since this runs in a script, I can't seem to accept the message and the script will hang at this point.  Would it be possible to implement a flag to automatically accept non opsec-safe modules for within scripts?  Such as using a flag such as --opsec [y/n]:
`cme smb /path/to/ips.txt -M enum_chrome --opsec y -d domain -u username -p password`

This is a bit of a mix of a limitation with CME but also, of course, a limitation within my script.  Just wanted to point this out and I think it would be a helpful feature for some users.

**Comment by byt3bl33d3r** [comment]
I'm kind of torn on this cause in one hand it kind of defeats the purpose  of the warning message if I add a way to bypass it but in the other I understand your use case.

I'll think about it a bit more and get back to you.
Thanks

**Comment by ebrinkster** [comment]
Thanks for the consideration.  I agree for both circumstances.  However, I think that having a flag with sufficient warning that you've "evaulated the opsec of modules" should be sufficient.  This would make scripting with CME much easier (at least for beginners, or those not using expect).

**Comment by ebrinkster** [comment]
Hey @byt3bl33d3r have you reconsidered implementing this to make this use case possible?

**Comment by Marshall-Hallenbeck** [comment]
I've created an option in the configuration file to ignore OPSEC prompts, and it tells you if this is enabled and an OPSEC-unsafe module is loaded.
Once tested and approved it will be released to the sponsors branch.

Ref: b945d51
