### ISSUE TITLE
File encoding + shebang for all Python files

### ISSUE THREAD

**Issue by maaaaz** [Porchetta-Industries/CrackMapExec#347]
Hello there,

First, good job for porting `cme` to Python3 !

Then, it's time to put a Python 3 shebang + encoding directive on every Python file to [avoid any stupid issue](https://docs.python.org//3/tutorial/interpreter.html) of that kind :
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
```

Starting with `setup.py`, which has a Python 2 shebang !

Cheers.

**Comment by byt3bl33d3r** [comment]
Good catch. We'll take a look to make sure they're all there.
