### ISSUE TITLE
Add hostname and IP in creds details

### ISSUE THREAD

**Issue by piratesofnetwork** [Porchetta-Industries/CrackMapExec#428]
Hi,

Could you please add the Hostname and IP address details in Creds details in CMEDB. that would help what creds/hash worked on which hostname/IP

**Comment by Marshall-Hallenbeck** [comment]
If you output by ID it prints out the IPs and hostnames that the creds have admin access to:

![image](https://user-images.githubusercontent.com/1518719/224559210-80e52da9-34ac-43d9-8007-7da4573a6401.png)
