### ISSUE TITLE
asyncio error when running

### ISSUE THREAD

**Issue by Bros10** [Porchetta-Industries/CrackMapExec#477]
I'm using crackmapexec on the latest version of Kali Linux and after running this command: `crackmapexec smb 192.168.10.18 -u users.txt -p Password123!` which did work perfectly. It now returns this error:
![image](https://user-images.githubusercontent.com/25135718/126177873-e293e5b8-9c0b-472b-af96-bdb41f65e04d.png)
I've updated python and all the libraries and reinstalled crackmapexec but still have had no success with fixing this error.

Any help would be appreciated!

**Comment by mpgn** [comment]
First time I see this error :'(

**Comment by bandrel** [comment]
Came here to bump this

**Comment by trevidia** [comment]
Maybe you aren't root

**Comment by bandrel** [comment]
I'm running as root

**Comment by Marshall-Hallenbeck** [comment]
@Bros10 @bandrel do you still get this issue?

**Comment by mpgn** [comment]
closing since no updated
