### ISSUE TITLE
error execution cme

### ISSUE THREAD

**Issue by tXambe** [Porchetta-Industries/CrackMapExec#599]
**Describe the bug**

When I run:
 ***cme smb -u -p –shares x.x.x.x***
```
I have this error:

Traceback (most recent call last):
  File "/home/vv/.local/bin/cme", line 5, in <module>
    from cme.crackmapexec import main
ModuleNotFoundError: No module named 'cme'
```

**To Reproduce**
```
1. run cme smb -u -p –shares x.x.x.x
```

**Expected behavior**

**Screenshots**

**Crackmapexec info**
 - OS: Linux K1 5.18.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali1 (2022-06-20) x86_64 GNU/Linux

 - Version of CME 
```
cme --version

Traceback (most recent call last):
  File "/home/vv/.local/bin/cme", line 5, in <module>
    from cme.crackmapexec import main
ModuleNotFoundError: No module named 'cme'

```

 - Installed from apt or using latest release ? Please try with latest release before openning an issue

I came installed with Kali

**Additional context**

**Comment by mpgn** [comment]
Sorry, I couldn't reproduce, make sure you install correctly

https://wiki.porchetta.industries/getting-started/installation/installation-on-unix
