### ISSUE TITLE
Ubuntu v5.3.0 Binary - Error: aardwolf library is missing

### ISSUE THREAD

**Issue by xel-dev** [Porchetta-Industries/CrackMapExec#602]
**Describe the bug**
On a fresh install of Ubuntu 22.04 LTS, the latest v5.3.0 binary does not seem to be working out of the box. Downloading and executing the `cme` binary within the `cme-ubuntu-latest.zip` archive results in the following error: 

`aardwolf librairy is missing, you need to install the submodule run the command:`

**To Reproduce**
Steps to repro:
1. Complete a minimal install of a fresh Ubuntu 22.04 LTS image
2. Run the following code:

```bash
# Update and upgrade 
sudo apt-get update
sudo apt -y upgrade

# Install CME
## Pull v5.3.0 zip file and unzip
wget https://github.com/Porchetta-Industries/CrackMapExec/releases/download/v5.3.0/cme-ubuntu-latest.zip
unzip ./cme-ubuntu-lastest.zip

## Add execution permission to binary, and execute binary
chmod +x ./cme
./cme
```
3. This should result in the following output:

```bash
[*] First time use detected
[*] Creating home directory structure
[*] Creating default workspace
[*] Initializing SMB protocol database
[*] Initializing LDAP protocol database
[*] Initializing WINRM protocol database
[*] Initializing RDP protocol database
[*] Initializing MSSQL protocol database
[*] Initializing SSH protocol database
[*] Copying default configuration file
[*] Generating SSL certificate
aardwolf librairy is missing, you need to install the submodule
run the command:
```

**Expected behavior**
Expected behaviour is for CME to work out of the box with no dependency issues after a fresh OS and application install.

**Screenshots**
N/A

**Crackmapexec info**
 - OS: Ubuntu 22.04 LTS
 - Version of CME: 5.3.0 - Operation C01NS
 - Installed from apt or using latest release? --> Latest release (binary)
 - Python Version: 3.10.4
 - Pip Version: pip 22.0.2

**Additional context**
N/A

**Comment by Reelix** [comment]
I came across the same issue on the latest Ubuntu.

https://github.com/Porchetta-Industries/CrackMapExec/blob/b39e82798479398750549cae2e64664fd05bfcc0/cme/protocols/rdp.py#L14-L16

It doesn't say which command to run.

**Comment by mpgn** [comment]
I will check, right now i'm very buzy :)

**Comment by mpgn** [comment]
I did try the binary but could not reproduce, can you test is again with the latest binary on this url depending of your python version: 

https://github.com/Porchetta-Industries/CrackMapExec/actions/runs/2623880891

**Comment by Reelix** [comment]
> https://github.com/Porchetta-Industries/CrackMapExec/actions/runs/2623880891

I can confirm that `cme-ubuntu-latest-3.10` from that link does indeed work.

Ubuntu Version: `Ubuntu 22.04 LTS`

Python Version: `Python 3.10.4`

**Comment by xel-dev** [comment]
> I did try the binary but could not reproduce, can you test it again with the latest binary on this url depending of your python version:
> 
> https://github.com/Porchetta-Industries/CrackMapExec/actions/runs/2623880891

I can confirm also confirm that the `cme-ubuntu-latest-3.10` binary from that link does work in the same environment (Ubuntu 22.04 LTS + Python 3.10.4) which I originally experienced bug (from the binary on the releases page). Thanks @mpgn! :)

**Comment by mpgn** [comment]
I just push the binaries on the release page https://github.com/Porchetta-Industries/CrackMapExec/releases/tag/v5.3.0

Thank you for the feedback :)
