### ISSUE TITLE
failed loading module at /usr/lib/python3/dist-packages/cme/modules/lsassy_dump.py cannot import name logger from lsassy

### ISSUE THREAD

**Issue by metasploit-ruined-my-life** [Porchetta-Industries/CrackMapExec#612]
i really didn't touched anything and i got this error when one of my penetration tests. i tried updating cme amd full system upgrade but nothing solved.

![cme](https://user-images.githubusercontent.com/62478273/182718156-4f1a7b24-99b4-4e99-b6ea-8809ca09fa62.PNG)

**Comment by Marshall-Hallenbeck** [comment]
Is this still an issue? This doesn't happen for me.

**Comment by mpgn** [comment]
closing since to old
