### ISSUE TITLE
Please update for latest aardwolf version (0.2.0)

### ISSUE THREAD

**Issue by sbrun** [Porchetta-Industries/CrackMapExec#651]
**Describe the bug**
aardwolf version 0.0.8 can't be packaged in Kali Linux because the license was missing. (https://github.com/skelsec/aardwolf/issues/4)
Upstream released a new version with a lot of changes. It can be packaged in Kali. But unfortunately CrackMapExec is not compatible with this version.
```aardwolf librairy is missing, you need to install the submodule```

**To Reproduce**
1. Install the latest release of crackmapexec
2. Install the latest release of aardwolf (0.2.0)
3. Run crackmapexec
```
aardwolf librairy is missing, you need to install the submodule
run the command:
```

**Crackmapexec info**
 - OS: Kali
 - Version of CME: v5.0.3
 - I built the package from source (from latest .tar.gz) for Kali and tested it.

**Additional context**
The failing import is
``` from aardwolf.commons.url import RDPConnectionURL ```
aardwolf.commons.url no longer exists in aardwolf

**Comment by mpgn** [comment]
Hello @sbrun yes I plan to migrate to the v2 soooonnnnnn :)

**Comment by mpgn** [comment]
I did some test today it will be ok :)

The plan: 

merge two awesome PR; #614  and #653 then pushing the RDP lib to 0.2.0 to CME and FIRE !!! :) 

ETA: end of next week

**Comment by mpgn** [comment]
@sbrun let's gooooo 💯

**Comment by mpgn** [comment]
I will push 5.4.0 in few hours

**Comment by mpgn** [comment]
Ok go :)

**Comment by mpgn** [comment]
Also aardwolf require rust on the system to work : `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Comment by mpgn** [comment]
Hello @sbrun it's already published since last week https://github.com/Porchetta-Industries/CrackMapExec/blob/master/pyproject.toml#L3 I'm waiting on you to make the official annonce and update the wiki !!!

**Comment by sbrun** [comment]
OK. Sorry. I misunderstood your previous message. I will work on this today.

**Comment by mpgn** [comment]
awesome thanks

**Comment by sbrun** [comment]
Just uploaded in Kali: it will be available in few hours for Kali users

**Comment by mpgn** [comment]
ok nice ! I will check when available if everything is working properly :)
