### ISSUE TITLE
Continue on success should stop trying an account already found

### ISSUE THREAD

**Issue by juliourena** [Porchetta-Industries/CrackMapExec#660]
When we use `--continue-on-success` we want to test all users with the different passwords we have, however, when we find a valid user if there are still passwords left in the list, they are still tested against the user that we already know his password. 

My suggestion is that once a valid password is found, do not continue testing that user, but skip to the next one.

```
crackmapexec smb 10.129.203.121 -u engels kiosko -p "Inlanefreight19!" "SimplePassword3!" --no-bruteforce --continue-on-success
SMB         10.129.203.121  445    DC01             [*] Windows 10.0 Build 17763 x64 (name:DC01) (domain:inlanefreight.htb) (signing:True) (SMBv1:False)
SMB         10.129.203.121  445    DC01             [+] inlanefreight.htb\engels:Inlanefreight19!
SMB         10.129.203.121  445    DC01             [-] inlanefreight.htb\engels:SimplePassword3! STATUS_LOGON_FAILURE 
SMB         10.129.203.121  445    DC01             [-] inlanefreight.htb\kiosko:Inlanefreight19! STATUS_LOGON_FAILURE 
SMB         10.129.203.121  445    DC01             [+] inlanefreight.htb\kiosko:SimplePassword3! 
```

**Comment by mpgn** [comment]
Hello,

Thanks for the issue, it is now fixed on the last public release of CrackMapExec https://github.com/mpgn/CrackMapExec v6.0.0

Regards,

mpgn
