### ISSUE TITLE
--continue on success flag being triggers despite not being set

### ISSUE THREAD

**Issue by Ourithi** [Porchetta-Industries/CrackMapExec#664]
## Steps to reproduce

1. use crackmapexec for winrm
2. 

## Command string used
└─$ crackmapexec -t 36  winrm 10.129.202.136   -u 'john' -p ./Password-Attacks/password.list 

## CME Version (cme --version)
5.2.2-0kali1

## OS
kali 2022.3

## Target OS
Windows 7.7
## Detailed issue explanation

When running cme for winrm, the program continues after cracking credentials despite the --continue-on-success flag not being set.

**Comment by mpgn** [comment]
Make sure you have the latest version of cme

**Comment by mpgn** [comment]
![image](https://user-images.githubusercontent.com/5891788/200516393-fe9b1a0a-7d5e-4bef-8192-f6c4c4c0b530.png)
