### ISSUE TITLE
--use-kcache doesn't work properly with smb 

### ISSUE THREAD

**Issue by embargod** [Porchetta-Industries/CrackMapExec#667]
**Describe the bug**
Issue with fully updated cme from source code
I have trouble with using `--use-kcache` along with the `smb` (yeah, i know about updated `-k` option and i could inetarct with kerberos without asktgt by third party tool) 

When using `smb` + `--use-kcache` can't see this structure `$DOMAIN\$USER` like with `ldap` protocol

**To Reproduce**
1. update source code  and `poetry`
2. get ticket with third party tool 
3. import `ccache` ticket
4. trying access to `smb` with ticket ->get strange output
5. trying access to `ldap` -> all works fine 
6. when trying to manipulate with any options and modules via `smb` i get errors
7. comparison with older version (when `-k` option was working with import ticket only) and newest version with fully updated source code

**Expected behavior**
See in `smb`  same structure like in `ldap` - `$DOMAIN\$USER`

**Screenshots**
![image](https://user-images.githubusercontent.com/62397547/199805189-e3c57d31-d94f-4837-9333-3b48d10b4a0d.png)

![image](https://user-images.githubusercontent.com/62397547/199803020-466867c4-bf2d-41f3-8e19-1d86231b98ff.png)

![image](https://user-images.githubusercontent.com/62397547/199803049-5b5f89ce-99e3-407e-ab18-f37e004fd3b2.png)

**Crackmapexec info**
 - Kali
 - Older Version of CME - 5.3.0 from release
 - Newest Version of CME from source code + poetry

**Comment by mpgn** [comment]
Confirmed, thanks for the report :) 

![image](https://user-images.githubusercontent.com/5891788/199823099-b1f39939-9f7a-4aab-a488-d0cd49f9fb7f.png)
