### ISSUE TITLE
Missing Binaries in Release

### ISSUE THREAD

**Issue by mueller** [Porchetta-Industries/CrackMapExec#683]
For the latest [`5.4.0` release](https://github.com/Porchetta-Industries/CrackMapExec/releases/tag/v5.4.0), there are no binaries in the assets section. I know, that it is possible to download them via the ["Actions"](https://github.com/Porchetta-Industries/CrackMapExec/actions/runs/3462698710), however, that is only possible when logged in to GitHub. 

This makes provisioning for VMs harder, since it is no longer easily possible to just download the latest release binary from the command line.

Would it be possible to upload the binaries to the assets section of the releases again?

**Comment by linuxkd** [comment]
@mueller, not sure if this is helpful or not, but here is how we grab and install the binaries in one of our build pipelines, maybe this is useful for you

```
#crackmapexec
echo "DEPLOYING CRACKMAPEXEC"
NAME="/tmp/cme.json"
mkdir /pentest/crackmapexec
cd /pentest/crackmapexec
curl -s https://api.github.com/repos/Porchetta-Industries/CrackMapExec/releases/latest -o $NAME
wget $(jq '.assets[] | select(.name | startswith("cme-ubuntu") and endswith("10.zip"))' $NAME | jq -r '.browser_download_url')
wget $(jq '.assets[] | select(.name | startswith("cmedb-ubuntu") and endswith("10.zip"))' $NAME | jq -r '.browser_download_url')
unzip cme-*.zip
chmod +x cme
ln -s /pentest/crackmapexec/cme /usr/local/bin/cme
ln -s /pentest/crackmapexec/cme /usr/local/bin/crackmapexec
cd -
```

**Comment by mpgn** [comment]
@mueller all done :)

**Comment by mueller** [comment]
Big Thanks! :)
