### ISSUE TITLE
Error while building using Docker Desktop "docker build" pointing directly to github master repository

### ISSUE THREAD

**Issue by alita87** [Porchetta-Industries/CrackMapExec#686]
docker build --no-cache -t cme https://github.com/Porchetta-Industries/CrackMapExec.git

Error while building: 
#7 43.55   × Building wheel for aardwolf (pyproject.toml) did not run successfully.
#7 43.55   │ exit code: 1
#7 43.55   ╰─> [625 lines of output]
#7 43.55       ['aardwolf', 'aardwolf.commons', 'aardwolf.examples', 'aardwolf.network', 'aardwolf.utils', 'aardwolf.transport', 'aardwolf.protocol', 'aardwolf.keyboard', 'aardwolf.extensions', 'aardwolf.commons.queuedata', 'aardwolf.commons.utils', 'aardwolf.examples.scanners', 'aardwolf.examples.scancommons', 'aardwolf.utils.rlers', 'aardwolf.utils.ducky', 'aardwolf.protocol.T125', 'aardwolf.protocol.vnc', 'aardwolf.protocol.T124', 'aardwolf.protocol.x224', 'aardwolf.protocol.pdu', 'aardwolf.protocol.fastpath', 'aardwolf.protocol.T128', 'aardwolf.protocol.T124.userdata', 'aardwolf.protocol.x224.client', 'aardwolf.protocol.x224.server', 'aardwolf.protocol.pdu.input', 'aardwolf.protocol.pdu.capabilities', 'aardwolf.keyboard.layouts', 'aardwolf.extensions.RDPECLIP', 'aardwolf.extensions.RDPECLIP.protocol']
[...]
#7 43.55       If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
[...]
ERROR: Could not build wheels for aardwolf, which is required to install pyproject.toml-based projects

**To Reproduce**
run docker desktop for windows
execute the following command: docker build --no-cache -t cme https://github.com/Porchetta-Industries/CrackMapExec.git

**Expected behavior**
Build crackmap image and be able to use it through docker desktop.

**Crackmapexec info**
 - OS: Windows 11, Docker desktop
 - github master repository
[stacktrace.txt](https://github.com/Porchetta-Industries/CrackMapExec/files/10065696/stacktrace.txt)

**Comment by mpgn** [comment]
Should be good :)

**Comment by kafkaesqu3** [comment]
Im still getting the same error as chemoms, from the latest from git pull (on a Ubuntu system)
