### ISSUE TITLE
The request can release the exe？

### ISSUE THREAD

**Issue by Baikeryoyo** [Porchetta-Industries/CrackMapExec#694]
I'm having trouble installing
When I execute pip install -r requirements.txt
Failed building wheel for aardwolf

**Comment by mpgn** [comment]
You need to install rust first

**Comment by Baikeryoyo** [comment]
> You need to install rust first

what? I didn't see this in the installation instructions
It tells me that I only need binary files and python

**Comment by mpgn** [comment]
the issue is hard to understand, closing for now until you explain a bit more
