### ISSUE TITLE
Not getting any output from any command

### ISSUE THREAD

**Issue by ampf27** [Porchetta-Industries/CrackMapExec#695]
I'm trying `cme smb <TARGET[s]> -u <USERNAME> -p <PASSWORD> -M multirdp` on my VM but not getting any result and the 445 and 3389 port is open

This also happens for any command/option I may try  and I don't get what may be the problem because the creadentials are correct.

**Comment by mpgn** [comment]
Because the target is not accessible or the port 445 is closed
