### ISSUE TITLE
Installing aardwolf failes on "poetry install"

### ISSUE THREAD

**Issue by corsch** [Porchetta-Industries/CrackMapExec#698]
**Describe the bug**

Since aarwolf 0.2.0 is required I am no longer able to install the latest cme version.

 poetry install

  • Installing aardwolf (0.2.0 d239c84): Building...
  • Installing aardwolf (0.2.0 d239c84): Failed

```
...
        error: failed to select a version for the requirement `pyo3 = "=0.16.6"`
        candidate versions found which didn't match: 0.16.5, 0.16.4, 0.16.3,
 ...
```

Does someone else have the same issue? 

**To Reproduce**
Kali Linux
git clone cme
poetry install 

**Expected behavior**
Clean installation of cme

**Crackmapexec info**
 - OS: Kali latest
 - Version of CME: git latest

**Additional context**
Same issue with the "private" porchetta release. (aardwolf 0.2.1)

**Comment by mpgn** [comment]
You need to install rust first

**Comment by mpgn** [comment]
yes install it with https://www.rust-lang.org/tools/install

**Comment by corsch** [comment]
Yes this did the trick. Thank you very much :)
