### ISSUE TITLE
Lsassy module Error

### ISSUE THREAD

**Issue by kluo84** [Porchetta-Industries/CrackMapExec#700]
**Describe the bug**
The error occurred while execute the lsassy module

**To Reproduce**
1. execute command  with a local admin -M lsassy
2. The error occurred below: (see screenshot)
**Expected behavior**
dump the LSASS process

**Screenshots**
![image](https://user-images.githubusercontent.com/15222944/206792718-bf762ddc-49c7-4e0c-afa3-fd4be9d5bac9.png)

**Crackmapexec info**
 - OS: kali Linux kali-core 6.0.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.7-1kali1 (2022-11-07) x86_64 GNU/Linux
 - Version of CME v5.4.0

**Comment by Marshall-Hallenbeck** [comment]
Does this error still get thrown? This works for me on 5.4.0

**Comment by mpgn** [comment]
closing since to ald
