### ISSUE TITLE
Feature Request : Kerberos module for username and password enum through Kerberos

### ISSUE THREAD

**Issue by Xyan1d3** [Porchetta-Industries/CrackMapExec#704]
I was wondering if it was possible to incorporate a new module like the existing `smb,winrm,mssql` named Kerberos which could validate usernames and passwords via Kerberos. Something similar to kerbrute.
As seen from the current problem kerbrute does not allow extensive password spraying, Some features like classic NTLM spray do not work on that.
Plus Kerbrute is a go binary which is not compatible with proxychains, whereas crackmapexec does.

Its just a request, BTW, I love this tool and use it every day on my journey to become a Red Teamer. Thank you @mpgn @byt3bl33d3r and all other contributors for bringing in and maintaining such a beautiful product kudos to you all :+1:

**Comment by mpgn** [comment]
You mean this: https://twitter.com/mpgn_x64/status/1587101999006351361
