### ISSUE TITLE
I get error when running crackmapexec on kali

### ISSUE THREAD

**Issue by xyplex** [Porchetta-Industries/CrackMapExec#708]
I keep geeting this when I run crackmapexec on kali 

![image](https://user-images.githubusercontent.com/45394257/209724442-e8b0258d-321d-4476-aa22-f4260a800925.png)

I have uninstalled and reinstalled crackmapexec but this has made no difference

sudo apt uninstall crackmapexec

sudo ap install crackmapexec

![image](https://user-images.githubusercontent.com/45394257/209724545-59a8b0b0-4e80-4620-8765-53b89a0afe42.png)

**Comment by BarHajby** [comment]
same here, update if you managed it

**Comment by NeffIsBack** [comment]
Have you tried installing CrackMapExec with pipx?
Might be a problem with your python installation. Is this a fresh kali?

**Comment by xyplex** [comment]
I uninstalled and reinstalled crackmapexec and still had the same issue.
My thoughts turned to python and as I was pretty sure it was not to do with crackmapexec.

I reinstalled Python3 and crackampexec worked correctly..

Thanks for your advice.
