### ISSUE TITLE
cannot load library 'libcrypto.so.1.1'

### ISSUE THREAD

**Issue by Adamkadaban** [Porchetta-Industries/CrackMapExec#718]
**Describe the bug**
Crackmapexec doesn't properly run when installed from snap.

**To Reproduce**
```bash
snap install core
snap install crackmapexec
```
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/34610663/211395648-cdf1dee1-73f2-488c-838d-5bc5d4ff7bc8.png)

**Crackmapexec info**
 - OS: Debian (Kernel 6.0.0-6-amd64)
 - Version of CME: Snap v5.4.0-21-g53c83f3
 - Installed from snap. 
 - 
**Additional context**
None

**Comment by Adamkadaban** [comment]
Installation worked using `pipx`: https://github.com/Porchetta-Industries/CrackMapExec/wiki/Installation

**Comment by mpgn** [comment]
Hello,

Thanks for the issue, it is now fixed on the last public release of CrackMapExec https://github.com/mpgn/CrackMapExec v6.0.0

Regards,

mpgn
