### ISSUE TITLE
after building cme a few modules are not availabe

### ISSUE THREAD

**Issue by FLX-0x00** [Porchetta-Industries/CrackMapExec#723]
After building cme using `build_collector.py` modules like "adcs" or "whoami" are not available when using cme with -M parameter and not listed by running with -L

**To Reproduce**
1. python build_collector.py

**Expected behavior**
All modules in the code listed are available when using cme

**Screenshots**
![image](https://user-images.githubusercontent.com/26464774/213422658-78986388-f854-410e-b8b7-cf4bf9b4212a.png)

**Crackmapexec info**
 - OS: Arch Linux
 - Version of CME: latest git
 - Installed from apt or using latest release: source (git)

**Additional context**
My plan was to check if docker builds are also affected but building the container from the current source is not possible. Think this is a debian issue?!
![image](https://user-images.githubusercontent.com/26464774/213424297-f5b788bc-aec0-4d9d-9308-4cb4d10464a4.png)

Sorry, that i am not able to provide more details atm.

**Comment by mpgn** [comment]
It depend of the protocol, module are not the same for LDAP and SMB :)

**Comment by FLX-0x00** [comment]
shame on me...where is the cat with the deep looking eyes showing only the pure disappointment.

**Comment by FLX-0x00** [comment]
![image](https://user-images.githubusercontent.com/26464774/213425672-418c8b86-ed66-4d4e-aac4-5a7fc7ac05c3.png)
