### ISSUE TITLE
ModuleNotFoundError: No module named 'librlers'

### ISSUE THREAD

**Issue by Cyb3rC3lt** [Porchetta-Industries/CrackMapExec#731]
**Describe the bug**
Essentially I download the latest binary version named 'Ubuntu cme-ubuntu-latest-3.11' and tried to run it on Kali.
It throws this missing module error named 'librlers' related to aardwolf but there is very little online in regards this library. Updated aardwolf to see if it would fix it but no joy. Any help would be greatly appreciated.

**To Reproduce**
cme smb $IP -u user -p 'pass'

**Expected behavior**
Start scanning

**Screenshots**
![image](https://user-images.githubusercontent.com/33097451/215067336-a59c3737-e3b4-4151-b7ca-245fa655416e.png)

**Crackmapexec info**
 - OS: Kali 2021.3
 - Version of CME v5.4.0
 - Downloaded Binary

**Comment by mpgn** [comment]
Hello, what's the result of python -v ?

**Comment by Cyb3rC3lt** [comment]
Hi there, thanks in advance for any guidance. Please find the outout requested below. Happy to provide more as I love this tool!

$ python -v                                                                                                            
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib/python2.7/site.pyc matches /usr/lib/python2.7/site.py
import site # precompiled from /usr/lib/python2.7/site.pyc
# /usr/lib/python2.7/os.pyc matches /usr/lib/python2.7/os.py
import os # precompiled from /usr/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib/python2.7/posixpath.pyc matches /usr/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib/python2.7/posixpath.pyc
# /usr/lib/python2.7/stat.pyc matches /usr/lib/python2.7/stat.py
import stat # precompiled from /usr/lib/python2.7/stat.pyc
# /usr/lib/python2.7/genericpath.pyc matches /usr/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib/python2.7/genericpath.pyc
# /usr/lib/python2.7/warnings.pyc matches /usr/lib/python2.7/warnings.py
import warnings # precompiled from /usr/lib/python2.7/warnings.pyc
# /usr/lib/python2.7/linecache.pyc matches /usr/lib/python2.7/linecache.py
import linecache # precompiled from /usr/lib/python2.7/linecache.pyc
# /usr/lib/python2.7/types.pyc matches /usr/lib/python2.7/types.py
import types # precompiled from /usr/lib/python2.7/types.pyc
# /usr/lib/python2.7/UserDict.pyc matches /usr/lib/python2.7/UserDict.py
import UserDict # precompiled from /usr/lib/python2.7/UserDict.pyc
# /usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc
# /usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py
import abc # precompiled from /usr/lib/python2.7/abc.pyc
# /usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc
# /usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py
import traceback # precompiled from /usr/lib/python2.7/traceback.pyc
# /usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc
# /usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py
import re # precompiled from /usr/lib/python2.7/re.pyc
# /usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc
# /usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc
import _locale # builtin
# /usr/lib/python2.7/_sysconfigdata.pyc matches /usr/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /usr/lib/python2.7/_sysconfigdata.pyc
# /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc matches /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py
import _sysconfigdata_nd # precompiled from /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc
# /usr/lib/python2.7/glob.pyc matches /usr/lib/python2.7/glob.py
import glob # precompiled from /usr/lib/python2.7/glob.pyc
# /usr/lib/python2.7/fnmatch.pyc matches /usr/lib/python2.7/fnmatch.py
import fnmatch # precompiled from /usr/lib/python2.7/fnmatch.pyc
# zipimport: found 12 names in /usr/share/offsec-awae-wheels/ply-3.11-py2.py3-none-any.whl
# zipimport: found 7 names in /usr/share/offsec-awae-wheels/backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
# zipimport: found 23 names in /usr/share/offsec-awae-wheels/requests-2.23.0-py2.py3-none-any.whl
# zipimport: found 13 names in /usr/share/offsec-awae-wheels/pyOpenSSL-19.1.0-py2.py3-none-any.whl
# zipimport: found 8 names in /usr/share/offsec-awae-wheels/PySocks-1.7.1-py27-none-any.whl
# zipimport: found 41 names in /usr/share/offsec-awae-wheels/urllib3-1.25.9-py2.py3-none-any.whl
# zipimport: found 11 names in /usr/share/offsec-awae-wheels/colorama-0.4.3-py2.py3-none-any.whl
# zipimport: found 48 names in /usr/share/offsec-awae-wheels/chardet-3.0.4-py2.py3-none-any.whl
# zipimport: found 6 names in /usr/share/offsec-awae-wheels/ipaddress-1.0.23-py2.py3-none-any.whl
# zipimport: found 23 names in /usr/share/offsec-awae-wheels/pycparser-2.20-py2.py3-none-any.whl
# zipimport: found 7 names in /usr/share/offsec-awae-wheels/enum34-1.1.10-py2-none-any.whl
# zipimport: found 22 names in /usr/share/offsec-awae-wheels/beautifulsoup4-4.9.1-py2-none-any.whl
# zipimport: found 13 names in /usr/share/offsec-awae-wheels/idna-2.9-py2.py3-none-any.whl
# zipimport: found 6 names in /usr/share/offsec-awae-wheels/six-1.15.0-py2.py3-none-any.whl
# zipimport: found 9 names in /usr/share/offsec-awae-wheels/certifi-2020.4.5.1-py2.py3-none-any.whl
# zipimport: found 11 names in /usr/share/offsec-awae-wheels/soupsieve-1.9.5-py2.py3-none-any.whl
# zipimport: found 40 names in /usr/share/cffi-wheels/py-1.8.1-py2.py3-none-any.whl
# zipimport: found 104 names in /usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl
# /usr/lib/python2.7/sitecustomize.pyc matches /usr/lib/python2.7/sitecustomize.py
import sitecustomize # precompiled from /usr/lib/python2.7/sitecustomize.pyc
# zipimport: found 53 names in /usr/local/lib/python2.7/dist-packages/shodan-1.26.1-py2.7.egg
import encodings # directory /usr/lib/python2.7/encodings
# /usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc
# /usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py
import codecs # precompiled from /usr/lib/python2.7/codecs.pyc
import _codecs # builtin
# /usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc
# /usr/lib/python2.7/encodings/utf_8.pyc matches /usr/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib/python2.7/encodings/utf_8.pyc
Python 2.7.18 (default, Sep 24 2021, 09:39:51) 
[GCC 10.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
dlopen("/usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so", 2);
import readline # dynamically loaded from /usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so
>>>

**Comment by mpgn** [comment]
Run the binary with python 3.11 if you dl the 3.11 binary of cme 😀

**Comment by Cyb3rC3lt** [comment]
Oh no that's embarrassing. I didn't think that was version numbers for various versions of Python for some reason and it was different versions of CME but of course CME is around version 5 so doesn't make sense. So for python 2.7 what would you recommend using? Thanks.

**Comment by mpgn** [comment]
Nothing, python2.7 is long dead since 2020 😅

**Comment by Cyb3rC3lt** [comment]
Haha fair enough, time for an upgrade
