### ISSUE TITLE
CMEDB is not grabbing creds

### ISSUE THREAD

**Issue by jrod1481** [Porchetta-Industries/CrackMapExec#745]
I had an issue where I had to re-install Crackmapexec to a kali machine. I used a pip install. Since then cmedb is not grabbing any creds and shows up blank. My thought is that its not chiming into that path or something to that degree. Would you know of an ideal way to get cmedb back working. Would it be as simple as an install of cmedb?

**Comment by mpgn** [comment]
Can you try without apt ? 

https://wiki.porchetta.industries/getting-started/installation/installation-on-unix
