### ISSUE TITLE
Verifying credentials fails with "[Errno 104] Connection reset by peer" when using any of the AES keys

### ISSUE THREAD

**Issue by jsdhasfedssad** [Porchetta-Industries/CrackMapExec#748]
**Description**
Verifying credentials using the NT hash works. However, when using any of the AES keys instead of the NT hash this fails with "[Errno 104] Connection reset by peer". 

**Screenshots**

![cme1](https://user-images.githubusercontent.com/97032878/220067275-852c570d-2b2e-45bd-94c2-f1ae35b1139b.png)

![cme2](https://user-images.githubusercontent.com/97032878/220067315-3cb687e5-946a-4ffe-858e-b447f45ce897.png)

**Crackmapexec info**
 - OS: Kali
 - Version of CME: 5.4.0

**Additional info**
CME reports the target as Windows 10. This is incorrect. The target is a Server 2019 fully patched.

**Comment by mpgn** [comment]
Can you try with latest versio 5.4.1, I don't recommand using the APT version of cme

https://wiki.porchetta.industries/getting-started/installation/installation-on-unix

**Comment by jsdhasfedssad** [comment]
I tried version 5.4.1 but I get the same error using that.

**Comment by mpgn** [comment]
I cannot reproduce on my side sorry
![image](https://user-images.githubusercontent.com/5891788/220109221-5b48fe6f-b744-439f-ac00-252d10ff696f.png)
