### ISSUE TITLE
crackmapexec /usr/lib/python3/dist-packages/pywerview/requester.py:144: SyntaxWarning: "is not" with a literal. Did you mean "!="?   if result['type'] is not 'searchResEntry':

### ISSUE THREAD

**Issue by 1Freezer** [Porchetta-Industries/CrackMapExec#756]
**Describe the bug**
I can not use crackmapexec due this issue

**To Reproduce**
1. Go to 'terminal'
2. Write crackmapexec smb IP
3. See error

**Expected behavior**
I need to use crackmapexec but I can not, i would like to fix this error

**Screenshots**
![image](https://user-images.githubusercontent.com/126933769/222873511-49d3a8d5-6714-4130-a661-1d11fc195510.png)

**Crackmapexec info**
 - OS: [e.g. Kali]
 - Version of CME [e.g. v5.0.2]
 - Installed from apt or using latest release ? Please try with latest release before openning an issue

**Additional context**
I tried to fix it by seeing the code, go to the file, and you have this code
![image](https://user-images.githubusercontent.com/126933769/222874234-0fd6ee1c-a345-4269-b35c-176859f077ca.png)
I tried writing != instead "is not", and then I tried to do it, nothing happens,I have no the error, but crackmapexec do nothing now, whitout any request

**Comment by NeffIsBack** [comment]
Please update crackmapexec, your version is way out of date. This Syntax version is fixed for several versions
