### ISSUE TITLE
poetry lock / poetry install

### ISSUE THREAD

**Issue by StayF0cus** [Porchetta-Industries/CrackMapExec#757]
Hello, when I run poetry lock or poetry install in my CrackMapExec folder I have this problem
"Project environment contains an invalid distribution"

![image](https://user-images.githubusercontent.com/49314617/223422837-25b82719-db17-4100-8bb0-3c3af9e30dbf.png)

Moreover, nothing happens

Any solution?

**Comment by twosevenzero** [comment]
Looks like this is a python/poetry issue and not an issue with CrackMapExec. 
According to [this issue](https://github.com/python-poetry/poetry/issues/6815) on the poetry repo, this is caused by leftover .dist-info files.

I am not able to replicate this issue.

```
$ poetry install
Creating virtualenv crackmapexec-uFAeCoN0-py3.11 in /home/zero/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 93 installs, 0 updates, 0 removals

  • Installing pycparser (2.21)
  • Installing asn1crypto (1.5.1)
  • Installing cffi (1.15.1)
  • Installing pycryptodomex (3.17)
    <-- SNIP -->
  • Installing terminaltables (3.1.10)
  • Installing xmltodict (0.12.0)

Installing the current project: crackmapexec (5.4.1)
```
