### ISSUE TITLE
Unable to load mimikatz

### ISSUE THREAD

**Issue by asadzz** [Porchetta-Industries/CrackMapExec#770]
**Describe the bug**
I'm using CME Version : 5.4.0  Codename: Indestructible G0thm0g on as 1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23).
When i try to load mimikatz using

`crackmapexec smb -M mimikatz` i get error

```
└─$ crackmapexec smb -M mimikatz   
[-] Module not found
```

**To Reproduce**
1. Go to shell run 'crackmapexec smb -M Mimikatz'
2. To verify the module is present i do 'ls' on /home/asad/.local/pipx/venvs/crackmapexec/lib/python3.10/site-packages/cme/modules, I can see the mimikatz.py file located in the folder

**Expected behavior**
crackmapexec smb -M mimikatz --module-info
I expect this to return module information, which I cannot see as the module is not loaded.

**Crackmapexec info**
 - OS: kali  6.1.12
 - Version of CME [e.g. v5.4.0]

**Additional context**

**Comment by mpgn** [comment]
Hello this module does not exist anymore and has been replaced by lsassy :)
