### ISSUE TITLE
CME provides no output if domain flag is out of order

### ISSUE THREAD

**Issue by BenKettlewell** [Porchetta-Industries/CrackMapExec#776]
**Describe the bug**
Crackmapexec will give no output and stop if the user, password and domain flags are not in the correct order.

**To Reproduce**
Breaks:  `crackmapexec smb -u someuser -d megacorp -p Password1 <ip>`
Works: `crackmapexec smb -u someuser -p Password1 -d megacorp <ip>`

**Expected behavior**
Runs the smb module against the target IP with creds provided

**Crackmapexec info**
 - OS: Kali
 - Version of CME: 5.4.0
 - Installed from apt or using latest release ? apt

**Comment by mpgn** [comment]
cme proto ip option

**Comment by mpgn** [comment]
Hello,

Thanks for the issue, it is now fixed on the last public release of CrackMapExec https://github.com/mpgn/CrackMapExec v6.0.0

Regards,

mpgn
